### ISSUE TITLE
Quick start is not working

### ISSUE THREAD

**Issue by JWDobken** [alexarchambault/ammonite-spark#138]
Try to run the quick-start example:

```cmd
❯ amm
Loading...
Welcome to the Ammonite Repl 2.1.4 (Scala 2.13.2 Java 13.0.2)
@ import $ivy.`org.apache.spark::spark-sql:2.4.0`
Failed to resolve ivy dependencies:Error downloading org.apache.spark:spark-sql_2.13:2.4.0
  not found: /Users/JDabke/.ivy2/local/org.apache.spark/spark-sql_2.13/2.4.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/2.4.0/spark-sql_2.13-2.4.0.pom
```

**Comment by alexarchambault** [comment]
@JWDobken You need to use scala 2.12.x. If you installed Ammonite via [the instructions on its website](http://ammonite.io/#Ammonite-REPL), you need to change `2.13` to `2.12` in the curl-ed URL. See [the instructions](https://github.com/alexarchambault/ammonite-spark/blob/master/README.md#quick-start) in the README of ammonite-spark else (I just updated them).

**Comment by JWDobken** [comment]
Thanks, I used homebrew to install Amonite (`brew install ammonite-repl`) which apparently defaults to 2.13
