### ISSUE TITLE
SparkSession vs AmmoniteSparkSession

### ISSUE THREAD

**Issue by manuzhang** [alexarchambault/ammonite-spark#30]
As per README

> The builder returned by AmmoniteSparkSession.builder() extends the one of SparkSession.builder(), so that one can call .appName("foo"), .config("key", "value"), etc. on it.

but I can create a `SparkSession` with `appName` and `config` on a local standalone Spark cluster. Is the above still true ?

**Comment by alexarchambault** [comment]
Just creating the session should work, but the classes generated from the REPL won't be accessible to the executors then. This shouldn't work anymore with it I think:
```scala
@ sc.parallelize(1 to 100, 10).map(_ + 1).sum()
```

**Comment by manuzhang** [comment]
I see. Why does it work with `spark-shell` ?

**Comment by alexarchambault** [comment]
spark-shell creates the SparkSession itself when it starts, and tweaks it a bit for the REPL (sets the URL of a small webserver it starts too, that serves the REPL class files, etc.).

Here, if users were to call `SparkSession.builder()` themselves, that extra tweaking, for Ammonite this time, wouldn't have been done. `AmmoniteSparkSession` handles it on the other hand.

**Comment by manuzhang** [comment]
Okay, is it possible to provide do that tweaking in almond ?
